# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "indexer"

service:
  type: LoadBalancer
  ports:
    - name: http # splunk-hec
      port: 9997
      protocol: TCP

livenessProbeEnabled: false
livenessProbe:
  tcpSocket:
    port: 9997
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 40
  failureThreshold: 1

readinessProbeEnabled: false
readinessProbe:
  tcpSocket:
    port: 9997
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 40
  failureThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
