apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk.fullname" . }}
  labels:
    app: {{ include "splunk.fullname" . }}
  {{- include "splunk.labels" . | nindent 4 }}
type: Opaque
data:
  splunkpassword: UGEkJHcwcmQ=